[deps]
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
Franklin = "713c75ef-9fc9-4b05-94a9-213340da978e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
